name: .NET Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
    - name: Restore dependencies
      run: dotnet restore ./backend/WebApp.sln
    - name: Build
      run: dotnet build ./backend/WebApp.sln --no-restore
    - name: Test
      run: dotnet test ./backend/WebApp.sln --no-build --verbosity normal
